## Mineração de *dados*

*Luiz Fernando Puttow Southier*<br>
*UTFPR-PB*

##Preenchimento de valores ausentes

In [1]:
import pandas as pd
import numpy as np

# Criar um DataFrame de exemplo com valores ausentes
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [np.nan, 2, 3, np.nan, 5],
        'C': [1, np.nan, np.nan, 4, 5]}

df = pd.DataFrame(data)

# Exibir o DataFrame original
print("DataFrame original:")
print(df)

# Preencher valores ausentes usando um valor específico (por exemplo, 0)
df_filled = df.fillna(0)

# Exibir o DataFrame com valores ausentes preenchidos
print("\nDataFrame com valores ausentes preenchidos:")
print(df_filled)

# Preencher valores ausentes usando a média das colunas
df_mean_filled = df.fillna(df.mean())

# Exibir o DataFrame com valores ausentes preenchidos pela média das colunas
print("\nDataFrame com valores ausentes preenchidos pela média das colunas:")
print(df_mean_filled)

DataFrame original:
     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  NaN  4.0
4  5.0  5.0  5.0

DataFrame com valores ausentes preenchidos:
     A    B    C
0  1.0  0.0  1.0
1  2.0  2.0  0.0
2  0.0  3.0  0.0
3  4.0  0.0  4.0
4  5.0  5.0  5.0

DataFrame com valores ausentes preenchidos pela média das colunas:
     A         B         C
0  1.0  3.333333  1.000000
1  2.0  2.000000  3.333333
2  3.0  3.000000  3.333333
3  4.0  3.333333  4.000000
4  5.0  5.000000  5.000000

##codificação de categórico para numérico (com ordem)

In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {'Tamanho': ['Grande', 'Médio', 'Pequeno', 'Médio', 'Pequeno', 'Grande']}
df = pd.DataFrame(data)

label_encoder = LabelEncoder()
df['Tamanho_encoded'] = label_encoder.fit_transform(df['Tamanho'])
df

   Tamanho  Tamanho_encoded
0   Grande                0
1    Médio                1
2  Pequeno                2
3    Médio                1
4  Pequeno                2
5   Grande                0

##codificação de categórico para numérico (sem ordem)

In [10]:
import pandas as pd

data = {'Cores': ['Vermelho', 'Verde', 'Azul', 'Azul', 'Verde', 'Vermelho']}
df = pd.DataFrame(data)

df_encoded = pd.get_dummies(df, columns=['Cores'], prefix=['Cor'])


df = pd.concat([df, df_encoded], axis=1)
df

      Cores  Cor_Azul  Cor_Verde  Cor_Vermelho
0  Vermelho         0          0             1
1     Verde         0          1             0
2      Azul         1          0             0
3      Azul         1          0             0
4     Verde         0          1             0
5  Vermelho         0          0             1

## Normalização da base de dados

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Dados de exemplo
data = {'Feature1': [10, 20, 30, 40, 50],
        'Feature2': [5, 15, 25, 35, 45]}

df = pd.DataFrame(data)

# Inicializar o scaler MinMax
scaler = MinMaxScaler()

# Normalização Min-Max
df_normalized = scaler.fit_transform(df)

# Converter o resultado normalizado em um DataFrame
df_normalized = pd.DataFrame(df_normalized, columns=df.columns)

print("Dados Originais:")
df

Dados Originais:

   Feature1  Feature2
0        10         5
1        20        15
2        30        25
3        40        35
4        50        45

In [5]:
print("\nDados Normalizados (MinMax):")
df_normalized

Dados Normalizados (MinMax):

   Feature1  Feature2
0      0.00      0.00
1      0.25      0.25
2      0.50      0.50
3      0.75      0.75
4      1.00      1.00

## Padronização da base de dados

In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Dados de exemplo
data = {'Feature1': [10, 20, 30, 40, 50],
        'Feature2': [5, 15, 25, 35, 45]}

df = pd.DataFrame(data)

# Inicializar o scaler Standardization
scaler = StandardScaler()

# Padronização
df_standardized = scaler.fit_transform(df)

# Converter o resultado padronizado em um DataFrame
df_standardized = pd.DataFrame(df_standardized, columns=df.columns)

print("Dados Originais:")
df

Dados Originais:

   Feature1  Feature2
0        10         5
1        20        15
2        30        25
3        40        35
4        50        45

In [7]:
print("\nDados Padronizados (Standardization):")
df_standardized

Dados Padronizados (Standardization):

   Feature1  Feature2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [8]:
df_standardized.describe()

       Feature1  Feature2
count  5.000000  5.000000
mean   0.000000  0.000000
std    1.118034  1.118034
min   -1.414214 -1.414214
25%   -0.707107 -0.707107
50%    0.000000  0.000000
75%    0.707107  0.707107
max    1.414214  1.414214